# Config file for automatic testing at travis-ci.org
sudo: false

language: python

cache: pip

python: 3.6

matrix:
  fast_finish: true
  
# Addons
addons:
  sonarcloud:
    organization: "openexo"

# install dependencies
install: pip install -r requirements_test.txt

# run tests on every Python version with tox
script: 
  - tox
  - sonar-scanner

# pypi deployment
deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  user: marfyl
  password: 
    secure: "dkmM5vfOqC2RxEA98SNuwP1xik/znGg9eLkbpI4R1zCZYUC95q8eA0qaMmT7K9yvpBNEhg2Q8pJUlZLm0nuGPC6wAEpvUkJ+qfRupDnT2tp3pUfLH3jOQj/Vqj3Dcee46sv68XniXju2QfQ+ylb+nV9KclLRGzAWkEm4ezmbQ9uD0TRqAjWhVfsvONlqA8iQWyiWGO1sukD6uQytRgPlEQ3aMrfHzRBi9rrAr+7035ho4MgxnRml4Ni7P54K8TF9IkFTBlxGTHEcDnf5fe3rvhF+WIdSb0r2SbYkL5dUdQFkCzlXsaRiq4X+MDIt1toAsANeB8enNFAuwCRdhgGmnuwgTdnwYrlgP8R+6fVj5qofDCTuLdQuT0qKdNlCaJNSK3ThMfXtStepkLx7KZ4pYmJTp7f/X56DMdy0bgl+c63sQDrctULBe4LwG4wBAJCSGedWaMixgftspPf/fwyUrMSSMncxgKmhxpslk6imqJ6n/+sgNFFHpxZmRZ6cKcfcdpe6BxvSEaoaybRXqdAVf8Mrj5n3utrnLI5WSwKmjmlxRhUZE+v+3pygxOiuFf/aAIT81uAti2qFNaFWqUZ3Bw8V7OqXWHD/YUIBnZUUg+/TWSpMcGOk08aH7/dCveu74pX9Yqknnp2ugHxCtmwjgwks08Z3XZLHopLCb+rD6hI="
  on:
    tags: true
    repo: exolever/django-typeform-feedback
    python: 3.6

after_success:
  - codecov
