# Config file for automatic testing at travis-ci.org
sudo: false

language: python

cache: pip

python: 3.6

matrix:
  fast_finish: true
  
# Addons
addons:
  sonarcloud:
    organization: "openexo"

# install dependencies
install: pip install -r requirements_test.txt

# run tests on every Python version with tox
script: 
  - tox
  - sonar-scanner

# pypi deployment
deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  user: marfyl
  password: 
    secure: "TgCT0C/IuhgK9BTs1vmpJuHmyGyevwkQO5Qgb/agGKEEVlwcIdyY0R+izu5EgmjCw+0d5jW9yY/yf6CqXcZUVuWJztgDdPfCwao2+HPJASjed8ThckMl6Hy4ujPgnMhn1l1X8CwfaSg8Nz9jjpLiaWJa4pmZgVwo4axPGqC+HH2rd5q5aMfK0RuVZ2nLhRTwSjhwCfvq8ScK/qC5Y+hsZcphAXO5y8tE5JSt3g+PkPkOiBky2cvwzcrDEWm+IBvFB6jmBVch36CND4mV+7byZcVC3Chy8UwcJKVFvEdQ9Qy/inQd2DwJJVOhbfCgZEDiEKag8GUb5Fs7nVZW+e3hP9bfzt7k7m3KY5sMkjYMMmYf236xrlVSuZFIJegbqcXz3uF9Cu/2jrDQZTsWpR6j1+SbxYPpH0KsHJiOVc3wOIObl09LzYTgexRZqyHKFEeE0NU8NcD5TF9xnwQtVwqUXQCZ/2vUX7yhSXBRtPXsNGLhahMwO+xq1vuvz6l97xd5y2eFY6ihUaX4g8vCIz3BOD+vQSsf5Cx58V0jbItKlUNU7VR1GW/akToWTDYepiN0MF7x56XsAJSHqttDxO9L+YZ30KBYiIzSrkFKcudwM1+7lAvEWTmI38SPRbuGEptzJRlh1St6gR5WnRlBN056CldqOWeYEJGHatZREgLAsEc="
  on:
    tags: true
    repo: exolever/django-typeform-feedback
    python: 3.6

after_success:
  - codecov
