sudo: false
dist: xenial
language: python
cache: pip
python:
python:
  - "3.7"
  - "3.6"
matrix:
  fast_finish: true
services:
  - postgresql
  - redis-server
addons:
  sonarcloud:
    organization: openexo
install: 
  - pip install -r requirements_test.txt
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - tox
  - sonar-scanner
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: marfyl
  password:
    secure: npcd6m0b+k+08TbauZxH2AXNFA7dOkTcYYXoY2AflAeeRgxtZA7bZ8uJdBwT0sg+A8WvSlRlu0FfS+7nb4CL6bUyFgRQJYv/0bDK5zy94w08eUvEHz6EJfnXFLuJQcbud9WlH8JfbmWhuFMscrdVwehhJadUtPYFfU2y46n5vovYheA6aG3tk7GZKWhoz7cUR8NJR8lr3BoojkSBkVVVz33sthFaZ8RGXsMB536uvgV8sYLjkKZvUBlPOFVTn113ncOwEdHAN5h1U2I2sGG9fJuqpVTZ8pqUI41heh8tYzPNCY61ga94tXlRxHDsnlLzJQ2PSuxGJuuWT5AZ5MPkTGAqep4EkCLe6XGgbbMV+ribFpNYgF3E0zFpRIWEO4K28JO4UQYlgVY/ij7B3vumJrJ/Av45D8igMCob71kyEcwXiLcxBev/bVEagp6nk70KxPVdZY90PT+dmFOpSH9ySRALRP2ytjFo1s2vu+zcKfCA4qJDc8K2+uPt6KRT/hiH26AyJNFYEdY0RhVwcwF9sABA2JoFjcf8+Ygdc5RcIsbT12qDv//yB1pOR1X05etG6TwzSGVrv899i1ZfWjYRNAqmDNZIIIfv41FdFs0eSC598G5nT3a4Tc22HtBv8n3w2SzU+4SMXfKXgJG9jfPEWpWvQ08yPnQd0lcQaIc/FBE=
  on:
    tags: true
    repo: exolever/django-typeform-feedback
    python: 3.6
after_success:
  - codecov
