# Generated by Django 2.2.5 on 2019-10-14 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foo',
            options={'verbose_name': 'Foo', 'verbose_name_plural': 'Foo'},
        ),
    ]
